# Nodes with values to reuse in the pipeline.
common_params:
  # Common plugin settings to use with the `plugins` key.
  - &common_plugins
    - automattic/bash-cache#2.16.0
  # Common environment values to use with the `env` key.
  - &common_env
    # Be sure to also update the `.xcode-version` file when updating the Xcode image/version here
    IMAGE_ID: xcode-14.3

steps:

  ######################
  # Build JS
  ######################
  - label: "🧪 Build JS"
    key: "bundle-js"
    command: .buildkite/build-js.sh
    plugins: *common_plugins
    artifact_paths:
      - "dist/**/*"

  ######################
  # Build iOS
  ######################
  - label: "🧪 Build iOS"
    command: .buildkite/build-ios.sh
    env: *common_env
    plugins: *common_plugins
    agents:
      queue: "mac"
    artifact_paths:
      - "dist/*.tar.gz"
      - "dist/*.zip"
      - "logs/**/*"

  ######################
  # Publish Android Artifacts
  ######################
  - label: "🧪 Build and upload Android Library to S3"
    command: .buildkite/publish-android.sh
    depends_on:
      - "bundle-js"
    plugins:
      - docker#v3.8.0:
          # Use a temporary Docker container that has both Android & Node setup
          # We're looking to remove the Docker usage as soon as possible.
          image: "public.ecr.aws/automattic/android-build-image:bc7c60a898d89d968aa8202c6b5bd08f91c1779e"
          propagate-environment: true
          environment:
            # DO NOT MANUALLY SET THESE VALUES!
            # They are passed from the Buildkite agent to the Docker container
            - "AWS_ACCESS_KEY"
            - "AWS_SECRET_KEY"
    agents:
      queue: "android"

  #################
  # Lint
  #################
  - label: "🧹 Lint (Rubocop)"
    command: make lint-ruby
