# Nodes with values to reuse in the pipeline.
common_params:
  # Common plugin settings to use with the `plugins` key.
  - &common_plugins
    - automattic/bash-cache#2.16.0
  # Common environment values to use with the `env` key.
  - &common_env
    # Be sure to also update the `.xcode-version` file when updating the Xcode image/version here
    IMAGE_ID: xcode-14.3

steps:

  ######################
  # Build JS
  ######################
  - label: "🧪 Build JS"
    command: .buildkite/build-js-docker.sh
    plugins: *common_plugins
    artifact_paths:
      - "dist/**/*"

  ######################
  # Build iOS
  ######################
  - label: "🧪 Build iOS"
    command: .buildkite/build-ios.sh
    env: *common_env
    plugins: *common_plugins
    agents:
      queue: "mac"
    artifact_paths:
      - "dist/*.tar.gz"
      - "logs/**/*"

  #################
  # Lint
  #################
  - label: "🧹 Lint (Rubocop)"
    command: make lint-ruby
