# Nodes with values to reuse in the pipeline.
common_params:
  # Common plugin settings to use with the `plugins` key.
  - &common_plugins
    - automattic/bash-cache#2.16.0
  # Common environment values to use with the `env` key.
  - &common_env
    # Be sure to also update the `.xcode-version` file when updating the Xcode image/version here
    IMAGE_ID: xcode-14.3

steps:

  ######################
  # Build JS
  ######################
  - label: "🧪 Build JS"
    key: "bundle-js"
    command: .buildkite/build-js.sh
    plugins: *common_plugins
    artifact_paths:
      - "dist/**/*"

  ######################
  # Build iOS
  ######################
  - label: "🧪 Build iOS"
    command: .buildkite/build-ios.sh
    env: *common_env
    plugins: *common_plugins
    agents:
      queue: "mac"
    artifact_paths:
      - "dist/*.tar.gz"
      - "logs/**/*"

  ######################
  # Publish Android Artifacts
  ######################
  #
  # Temporarily disable publishing Android artifacts because we need a more up to date 
  # version of `glibc` in our Android agents. This should be available once Buildkite
  # base image switches to Amazon Linux 2023:
  # https://github.com/buildkite/elastic-ci-stack-for-aws/pull/1122
  #
  # If we get blocked by publishing Android artifacts, we can temporarily switch to using
  # Docker in which case the `add/node` branch of 
  # https://github.com/wordpress-mobile/docker-android-build-image might be useful.
  #
  #  - label: "🧪 Build and upload Android Library to S3"
  #    command: .buildkite/publish-android.sh
  #    depends_on:
  #      - "bundle-js"
  #    plugins: *common_plugins
  #    agents:
  #      queue: "android"
  #    if: "build.tag != null || build.pull_request.id != null || build.branch == 'trunk'"

  #################
  # Lint
  #################
  - label: "🧹 Lint (Rubocop)"
    command: make lint-ruby
